### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by GingerNinjaa** [KemberlyMiliano/JustBeerApp#1]
Hi,

I found this project reading XamGirl Blog, and this is amazing!!! I relay want to try this app buy i have issue with API because when I swap api key o my own this app dont work. Yes its opening but there is no "beer data".

Could you help me with that issue?

Please contact me belowe this post or on my email address damian.lewandowski.dev@gmail.com

Best Regards
Damian Lewandowski

**Comment by KemberlyMiliano** [comment]
I tested the app again with a new API key and is working fine.

public const string ApiKey = "?key=**YOURAPIKEY**";

This is the way your API key cosnt should go, maybe the way I wrote the instructions wasn't very clear.

**Comment by alxsboom** [comment]
how can i use this? it says invalid fingerprint. thanks for helping

**Comment by KemberlyMiliano** [comment]
Updating some packages and changing the ApiKey should be enough for the app to work. Where are you getting this error?
